summary: PG Explorer
value:
  fullscreen: false
  grid:
    - '12':
        fixed: true
        fullHeight: false
        h: 2
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: true
        fullHeight: false
        h: 2
        w: 6
        x: 0
        'y': 0
      id: topbar
      data:
        id: topbar
        type: containercomponent
        actions: []
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 14
        w: 12
        x: 0
        'y': 2
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 2
        x: 0
        'y': 2
      id: a
      data:
        id: a
        type: dbexplorercomponent
        actions: []
        configuration:
          type:
            type: oneOf
            configuration:
              bigquery:
                resource:
                  type: static
                  value: ''
                table:
                  type: static
              ms_sql_server:
                resource:
                  type: static
                  value: ''
                table:
                  type: static
              mysql:
                resource:
                  type: static
                  value: ''
                table:
                  type: static
              postgresql:
                resource:
                  type: static
                  value: '$res:f/db/tonka_main_pg'
                table:
                  type: static
                  value: products
                  loading: false
                  selectOptions:
                    - cart_items
                    - products
                    - inventory
                    - coupons
                    - users
                    - product_reviews
                    - payment_methods
                    - product_variants
                    - orders
                    - order_items
                    - addresses
                    - categories
                    - cart
                    - order_statuses
                    - order_coupons
              snowflake:
                resource:
                  type: static
                  value: ''
                table:
                  type: static
            selected: postgresql
          allEditable:
            type: static
            value: false
          allowDelete:
            type: static
            value: false
          columnDefs:
            type: static
            value:
              - datatype: integer
                defaultvalue: 'nextval(''products_product_id_seq''::regclass)'
                field: product_id
                isenum: null
                isidentity: 'No'
                isnullable: 'NO'
                isprimarykey: true
              - datatype: integer
                defaultvalue: null
                field: category_id
                isenum: null
                isidentity: 'No'
                isnullable: 'YES'
                isprimarykey: false
              - datatype: character varying(200)
                defaultvalue: null
                field: name
                isenum: null
                isidentity: 'No'
                isnullable: 'NO'
                isprimarykey: null
              - datatype: text
                defaultvalue: null
                field: description
                isenum: null
                isidentity: 'No'
                isnullable: 'YES'
                isprimarykey: null
              - datatype: 'numeric(10,2)'
                defaultvalue: null
                field: price
                isenum: null
                isidentity: 'No'
                isnullable: 'NO'
                isprimarykey: null
              - datatype: character varying(50)
                defaultvalue: null
                field: sku
                isenum: null
                isidentity: 'No'
                isnullable: 'YES'
                isprimarykey: false
              - datatype: character varying(255)
                defaultvalue: null
                field: image_url
                isenum: null
                isidentity: 'No'
                isnullable: 'YES'
                isprimarykey: null
              - datatype: boolean
                defaultvalue: 'true'
                field: is_active
                isenum: null
                isidentity: 'No'
                isnullable: 'YES'
                isprimarykey: null
              - datatype: timestamp without time zone
                defaultvalue: CURRENT_TIMESTAMP
                field: created_at
                isenum: null
                isidentity: 'No'
                isnullable: 'NO'
                isprimarykey: null
              - datatype: timestamp without time zone
                defaultvalue: null
                field: updated_at
                isenum: null
                isidentity: 'No'
                isnullable: 'YES'
                isprimarykey: null
            loading: false
          customActionsHeader:
            type: static
          extraConfig:
            type: static
            value: {}
          flex:
            type: static
            value: true
          footer:
            type: static
            value: true
          hideInsert:
            type: static
            value: false
          hideSearch:
            type: static
            value: false
          multipleSelectable:
            type: static
            value: false
          rowIdCol:
            type: static
            value: ''
          rowMultiselectWithClick:
            type: static
            value: true
          selectFirstRowByDefault:
            type: static
            value: true
          whereClause:
            type: static
            value: ''
          wrapActions:
            type: static
            value: false
        customCss:
          container:
            class: ''
            style: ''
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    topbar-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        id: title
        data:
          id: title
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections:
              - id: summary
                componentId: ctx
            eval: '${ctx.summary}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 6
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          'y': 1
        id: recomputeall
        data:
          id: recomputeall
          type: recomputeallcomponent
          actions: []
          configuration:
            defaultRefreshInterval:
              type: static
              value: '0'
          customCss:
            container:
              class: ''
              style: ''
          horizontalAlignment: right
          menuItems: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  allowed_s3_keys: []
  execution_mode: publisher
  s3_inputs: []
  triggerables_v2:
    'a_count:rawscript/2a3aa490b7ab1eaff0385c76a0f81dce44d27265cd2cd98d6186ff91a64bd655':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs:
        database: '$res:f/db/tonka_main_pg'
    'a_delete:rawscript/c050c1b422f5371ec547692d4c85519af671c9aa16074bc8a17e9cca07e4f92e':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs:
        database: '$res:f/db/tonka_main_pg'
    'a_insert:rawscript/495dd15ec2071cb302c51b84b77b324d2fabe2b85047ea102e4f17b83edeaec8':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs:
        database: '$res:f/db/tonka_main_pg'
    'a:rawscript/3df2738951e277ad842e406853fea725c1e255c9c86d5a2dee2d1bfaba57f244':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs:
        database: '$res:f/db/tonka_main_pg'
