/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Categories {
  category_id: Generated<number>;
  created_at: Generated<Timestamp>;
  description: string | null;
  name: string;
}

export interface Inventory {
  inventory_id: Generated<number>;
  last_updated: Generated<Timestamp>;
  product_id: number;
  quantity: Generated<number>;
}

export interface Products {
  category_id: number | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  image_url: string | null;
  is_active: Generated<boolean | null>;
  name: string;
  price: Numeric;
  product_id: Generated<number>;
  sku: string | null;
  updated_at: Timestamp | null;
}

export interface ProductVariants {
  additional_price: Generated<Numeric | null>;
  color: string | null;
  inventory_count: Generated<number>;
  product_id: number;
  size: string | null;
  variant_id: Generated<number>;
}

export interface DB {
  categories: Categories;
  inventory: Inventory;
  product_variants: ProductVariants;
  products: Products;
}
